name: multitask_research
description: A new Flutter project.
version: 1.2.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+3
  material_design_icons_flutter: ^3.4.4995
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 700

        


