on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
        channel: 'stable'
    - run: flutter pub get
    - run: echo $DART_KEYS >> lib/KEYS.dart
      shell: bash
      env:
        DART_KEYS : ${{secrets.KEYS}}
    - run: flutter build web
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: common-research
        channelId: deploy-test
